updated publish prod workflow

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -4,6 +4,10 @@ env:
   REPO_OWNER_USERNAME: ${{ secrets.REPO_OWNER_USERNAME }}
 
 on:
+  push:
+    tags:
+      - v*
+
   workflow_dispatch:
     permissions:
       users:
@@ -14,7 +18,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up Python
         uses: actions/setup-python@v2
@@ -53,8 +57,8 @@ jobs:
         id: check_version
         run: |
           LAST_VERSION=$(grep "__version__ = .*" nsdpy.py | sed " s/__version__ = //")
-          echo "version is $LAST_VERSION"
-          if grep -q ".*-beta$" <<< "$LAST_VERSION"; then
+          echo "last version is $LAST_VERSION"
+          if echo "$LAST_VERSION" | grep -q ".*-beta$"; then
           echo "Version is not a test version: should end with -beta"
           exit 1
           fi
@@ -66,38 +70,36 @@ jobs:
         id: increment_version_and_check_tag
         run: |
           LAST_VERSION=${{ steps.check_version.outputs.last_version }}
-          echo "result of last version: $LAST_VERSION"
+          echo "looking for a matching tag..."
           git fetch --tags --quiet
           TAG_EXISTS=$(git tag -l "$LAST_VERSION")
           if [ -z "$TAG_EXISTS" ]; then
           echo "No matching tags found for version $LAST_VERSION"
           exit 1
           fi
-          echo "Matching tags: $TAG_EXISTS"
+          echo "matching tag $TAG_EXISTS found"
+          echo "checking tag isSemVer..."
+          SEMVER="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
+          if echo "$TAG_EXISTS" | grep -qP "$SEMVER"; then
+          echo "$TAG_EXISTS is not SemVer-compliant"
+          exit 1
+          fi
+          echo "$TAG_EXISTS is SemVer-compliant"
           echo "tags=$TAG_EXISTS" >> $GITHUB_OUTPUT
 
-      #     echo "::set-output name=new_version::$NEW_VERSION"
-      #     echo "::set-output name=tag_exists::$TAG_EXISTS"
-
-      # - name: Update Version and Files
-      #   if: steps.increment_version_and_check_tag.outputs.tag_exists != '1'
-      #   run: |
-      #     NEW_VERSION=${{ steps.increment_version_and_check_tag.outputs.new_version }}
-      #     sed -i "s/__version__ = .*/__version__ = \"$NEW_VERSION\"/" nsdpy.py
-      #     poetry version $NEW_VERSION
-      #     git config --global user.email "github-actions@gg.com"
-      #     git config --global user.name "GitHub Actions"
-      #     git commit -am "Bump version to $NEW_VERSION [skip ci]"
-      #     git push origin $BRANCH_NAME
-
-      # - name: Create Tag and Push
-      #   if: steps.increment_version_and_check_tag.outputs.tag_exists != '1'
-      #   run: |
-      #     NEW_VERSION=${{ steps.increment_version_and_check_tag.outputs.new_version }}
-      #     BRANCH_NAME=${GITHUB_REF##*/}
-      #     COMMIT_SHA=$(git rev-parse HEAD)
-      #     git tag -a $NEW_VERSION -m "Version $NEW_VERSION, Branch: $BRANCH_NAME, Commit: $COMMIT_SHA"
-      #     git push origin $NEW_VERSION
+      - name: Check Documentation Version
+        id: check_doc_version
+        run: |
+          echo "checking documentation version..."
+          LAST_VERSION=${{ steps.check_version.outputs.last_version }}
+          DOC_VERSION=$(grep "release = .*" docs/conf.py | sed " s/release = //")
+          echo "documentation is versioned with $DOC_VERSION"
+          if [[ "$LAST_VERSION"  != "$DOC_VERSION" ]]; then
+          echo "ERROR: documentation version is not up to date !"
+          exit 1
+          fi
+          echo "documentation is up to date"
+          echo "documentation_version=$DOC_VERSION" >> $GITHUB_OUTPUT
 
       - name: Build and Publish to PyPI Test
         env:
@@ -106,6 +108,6 @@ jobs:
         run: |
           echo $BOT_ACCESS_TOKEN
           poetry build
-          poetry config repositories.test-pypi https://test.pypi.org/legacy/
-          poetry config pypi-token.test-pypi $BOT_ACCESS_TOKEN
-          poetry publish -r test-pypi
+          poetry config repositories.pypi https://pypi.org/
+          poetry config pypi-token.pypi $BOT_ACCESS_TOKEN
+          poetry publish -r pypi
